routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BannerController;
use App\Http\Controllers\CouponController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\WishlistController;
use App\Http\Controllers\ListBannerController;
use App\Http\Controllers\FetureBanneController;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\SingleBannerController;
use App\Http\Controllers\Backend\BrandController;
use App\Http\Controllers\Backend\OrderController;
use App\Http\Controllers\Frontend\CartController;
use App\Http\Controllers\Backend\AboutUsController;
use App\Http\Controllers\Backend\BackendController;
use App\Http\Controllers\Backend\OurTeamController;
use App\Http\Controllers\Backend\ProductController;
use App\Http\Controllers\Backend\SettingController;
use App\Http\Controllers\Backend\CategoryController;
use App\Http\Controllers\Backend\ShippingController;
use App\Http\Controllers\Frontend\CheckOutController;
use App\Http\Controllers\Frontend\FrontendController;
use App\Http\Controllers\Backend\SubCategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [FrontendController::class, 'index'])->name('front.index');
Route::get('/categories/{slug}', [FrontendController::class, 'categories'])->name('front.categories');
Route::get('/single-product/{slug}', [FrontendController::class, 'singleProduct'])->name('single.product');
Route::get('/product-brand/{slug}', [FrontendController::class, 'productBrand'])->name('product.brand');
Route::post('/quick-view', [FrontendController::class, 'quickView'])->name('quick.view');

// review section
Route::post('/product-review/{slug}', [FrontendController::class, 'productriview'])->name('review.store');

Route::get('/user/login', [FrontendController::class, 'userLogin'])->name('user.login');
Route::post('/user/submit', [FrontendController::class, 'loginSubmit'])->name('login.submit');
Route::post('/register/submit', [UserController::class, 'store'])->name('register.submit');
Route::get('/user/logout', [FrontendController::class, 'userLogout'])->name('user.logout');

// Auto Search Section
Route::get('auto-search', [FrontendController::class, 'autoSearch'])->name('auto.search');
Route::post('search', [FrontendController::class, 'search'])->name('search');

//WishList section
Route::get('wishlists', [WishlistController::class, 'create'])->name('wishlist');
Route::post('wishlist/store', [WishlistController::class, 'store'])->name('wish.store');
Route::post('wishlist/delete', [WishlistController::class, 'delete'])->name('wishlist.delete');
Route::post('move-to-cart', [WishlistController::class, 'moveToCart'])->name('move.cart');

// CheckOut Section Start
Route::get('check-out', [CheckOutController::class, 'checkOut1'])->name('chechkout1');
Route::post('checkout-one', [CheckOutController::class, 'checkOut1Store'])->name('checkout1.store');
Route::post('checkout-two', [CheckOutController::class, 'checkOut2Store'])->name('checkout2.store');
Route::post('checkout-three', [CheckOutController::class, 'checkOut3Store'])->name('checkout3.store');
Route::post('checkout-four', [CheckOutController::class, 'checkOut4Store'])->name('checkout4.store');
Route::get('checkout-complete/{order}', [CheckOutController::class, 'checkOutComplete'])->name('checkout.complete');

//cart Section
Route::post('user/cart/store', [CartController::class, 'cartStore'])->name('cart.store');

Route::post('product-details', [FrontendController::class, 'sizeFilter'])->name('size.filter');

// About us
Route::get('about-us', [FrontendController::class, 'aboutUs'])->name('about.us');
// Contact Section
Route::get('contact-us', [FrontendController::class, 'contactUs'])->name('contactUs');
Route::post('contact', [ContactController::class, 'contactStore'])->name('contact.store');
// Shop Section
Route::get('shop', [FrontendController::class, 'shop'])->name('shop');
Route::post('shop-filter', [FrontendController::class, 'shopFilter'])->name('shop.filter');

Route::group(['prefix' => 'user', 'middleware' => 'auth'], function () {
    Route::get('dashboard', [UserController::class, 'userAccount'])->name('user.dashboard');


    //cart Section
    Route::post('cart/delete', [CartController::class, 'cartDelete'])->name('cart.delete');
    Route::get('cart/details', [CartController::class, 'cartDetails'])->name('cart.details');
    Route::post('cart-update', [CartController::class, 'cartUpdate'])->name('cart.update');

    // coupon section
    Route::post('coupon-add', [CartController::class, 'couponAdd'])->name('coupon.addd');



    //update user Section
    Route::get('orders', [UserController::class, 'userOrder'])->name('user.orders');
    Route::get('account-deatils', [UserController::class, 'userDeatils'])->name('user.deatils');
    Route::post('update-user-address/{id}', [UserController::class, 'updateAdress'])->name('userAddress.update');
    Route::post('update-account/{id}', [UserController::class, 'updateAccount'])->name('update.account');
    Route::get('wishlists', [UserController::class, 'userWishlist'])->name('user.wishlist');

    // coupon Controller
    Route::resource('cupon', CouponController::class);
    Route::post('coupon-status', [CouponController::class, 'couponStatus'])->name('coupon.status');
});


// Backend Section
Route::group(['prefix' => 'dashboard', 'middleware' => ['auth', 'admin']], function () {
    Route::get('/', [BackendController::class, 'index'])->name('dashboard.index');

    // Category Route
    Route::resource('categories', CategoryController::class);
    Route::post('categories-status', [CategoryController::class, 'categoryStatus'])->name('category.status');


    //Sub Category Route
    Route::resource('sub-categories', SubCategoryController::class);
    Route::post('sub-categories-status', [SubCategoryController::class, 'subCategoryStatus'])->name('subCategory.status');
    // Route::get('get-sub-categories/{id}', [SubCategoryController::class, 'subCategory']);

    //Brand Route
    Route::resource('brand', BrandController::class);
    Route::post('brand-status', [BrandController::class, 'brandStatus'])->name('brand.status');

    //Product Route
    Route::resource('products', ProductController::class);
    Route::post('products-status', [ProductController::class, 'productStatus'])->name('product.status');

    // Product Attribute section
    Route::get('add-product-attribute/{id}', [ProductController::class, 'productAttribute'])->name('product.attribute');
    Route::post('product-attribute-store/{id}', [ProductController::class, 'attributeStore'])->name('attribute.store');
    Route::get('product-attributes', [ProductController::class, 'attributeList'])->name('productAttr.index');
    Route::delete('product-attribute-delete/{id}', [ProductController::class, 'attributeDelete'])->name('attribute.delete');

    //User Route
    Route::resource('user', UserController::class);
    Route::post('user-type', [UserController::class, 'userType'])->name('user.type');

    //Banner Route
    Route::resource('banners', BannerController::class);
    Route::post('banners-status', [BannerController::class, 'bannerStatus'])->name('banner.status');

    // Single Banner
    Route::resource('single-banner', SingleBannerController::class);
    Route::post('single-banners-status', [SingleBannerController::class, 'singleStatus'])->name('single.status');

    // List Banner Route
    Route::resource('list-banner', ListBannerController::class);
    Route::post('list-banner-status', [ListBannerController::class, 'listBannerStatus'])->name('list-banner.status');

    // Feature product banner

    // Route::resource('feature-banner', FetureBanneController::class);
    Route::get('feature-banner/create', [FetureBanneController::class, 'create'])->name('feature-banner.create');
    Route::post('feature-banner', [FetureBanneController::class, 'store'])->name('feature-banner.store');
    Route::get('feature-banner', [FetureBanneController::class, 'index'])->name('feature-banner.index');
    Route::get('feature-banner/{id}', [FetureBanneController::class, 'show'])->name('feature-banner.show');
    Route::get('feature-banner/{id}/edit', [FetureBanneController::class, 'edit'])->name('feature-banner.edit');
    Route::put('feature-banner/{id}', [FetureBanneController::class, 'update'])->name('feature-banner.update');
    Route::delete('feature-banner/{id}', [FetureBanneController::class, 'destroy'])->name('feature-banner.destroy');

    Route::post('feature-status', [FetureBanneController::class, 'featureStatus'])->name('feature.status');

    //Order Section
    Route::resource('order', OrderController::class);
    Route::post('order-status', [OrderController::class, 'orderStatus'])->name('order.status');
    Route::get('order-search', [OrderController::class, 'orderSearch'])->name('order.search');

    //Setting Section
    Route::get('setting', [SettingController::class, 'settingEdit'])->name('setting.edit');
    Route::post('setting', [SettingController::class, 'settingStore'])->name('setting.store');

    // Shippiong Route
    Route::resource('shippings', ShippingController::class);
    Route::post('shipping-status', [ShippingController::class, 'shippingStatus'])->name('shipping.status');

    // About us Section
    Route::get('about-us-create', [AboutUsController::class, 'edit'])->name('about.create');
    Route::post('about-us', [AboutUsController::class, 'aboutUpdate'])->name('aboutus.store');

    // Team Membar Secction
    Route::resource('teams', OurTeamController::class);
    Route::get('member-details/{id}', [OurTeamController::class, 'show'])->name('member.show');

resources/views/backend/modules/team/create.blade.php
@extends('backend.layout.master')
@section('title', 'Add Team Member')
@section('contant')
    <div class="row justify-content-center mt-4">
        <div class="col-lg-6">
            <div class="card">
                <div class="card-header">
                    <h4>@yield('title')</h4>
                </div>
                <div class="card-body">
                    {!! Form::open(['route' => 'teams.store', 'method' => 'post', 'files' => true]) !!}
                    @include('backend.modules.team.form');
                    {!! Form::button('submit', ['class' => 'btn btn-sm btn-success mt-4', 'type' => 'submit']) !!}
                    {!! Form::close() !!}
                </div>
            </div>

        </div>
    </div>
@endsection

resources/views/backend/modules/team/edit.blade.php
@extends('backend.layout.master')
@section('title', 'Update Team Member')
@section('contant')
    <div class="row mt-3 justify-content-center">
        <div class="col-lg-6">
            <div class="card">
                <div class="card-header">@yield('title')</div>
                <div class="card-body">
                    {!! Form::model($ourTeam, ['method' => 'put', 'route' => ['member.update', $ourTeam->id], 'files' => true]) !!}
                    @include('backend.modules.team.form');
                    <div class="member-img">
                        <img src="{{ asset('image/team/' . $ourTeam->photo) }}" alt="">
                    </div>
                    {!! Form::button('submit', ['class' => 'btn btn-sm btn-success mt-4', 'type' => 'submit']) !!}
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/modules/team/form.blade.php
{!! Form::label('name', 'Name') !!}
{!! Form::text('name', null, ['class' => 'form-control form-control-sm', 'placeholder' => 'Membar Name..']) !!}
@error('name')
    <p class="text-danger position-absolute"><small>{{ $message }}</small></p>
@enderror

{!! Form::label('skills', 'Skills', ['class' => 'mt-4']) !!}
{!! Form::text('skills', null, ['class' => 'form-control form-control-sm', 'placeholder' => 'member skills..']) !!}
@error('skills')
    <p class="text-danger position-absolute"><small>{{ $message }}</small></p>
@enderror

{!! Form::label('email', 'Email', ['class' => 'mt-4']) !!}
{!! Form::email('email', null, [
    'class' => 'form-control form-control-sm',
    'placeholder' => 'e.g member@gmail.com',
]) !!}
@error('skills')
    <p class="text-danger position-absolute"><small>{{ $message }}</small></p>
@enderror

{!! Form::label('status', 'Status', ['class' => 'mt-4']) !!}
{!! Form::select('status', [1 => 'Active', 2 => 'Inactive'], null, [
    'class' => 'form-select form-select-sm',
    'placeholder' => 'Select member status',
]) !!}
@error('status')
    <p class="text-danger position-absolute"><small>{{ $message }}</small></p>
@enderror

{!! Form::label('fb_link', 'FaceBook Link', ['class' => 'mt-4']) !!}
{!! Form::text('fb_link', null, [
    'class' => 'form-control form-control-sm',
    'placeholder' => 'fb_link...',
]) !!}
@error('fb_link')
    <p class="text-danger position-absolute"><small>{{ $message }}</small></p>
@enderror

{!! Form::label('twitter_link', 'Twitter Link', ['class' => 'mt-4']) !!}
{!! Form::text('twitter_link', null, [
    'class' => 'form-control form-control-sm',
    'placeholder' => 'twitter_link...',
]) !!}
@error('twitter_link')
    <p class="text-danger position-absolute"><small>{{ $message }}</small></p>
@enderror

{!! Form::label('linkdin_link', 'Linkdin Link', ['class' => 'mt-4']) !!}
{!! Form::text('linkdin_link', null, [
    'class' => 'form-control form-control-sm',
    'placeholder' => 'linkdin_link...',
]) !!}
@error('linkdin_link')
    <p class="text-danger position-absolute"><small>{{ $message }}</small></p>
@enderror

{!! Form::label('google_link', 'Google Link', ['class' => 'mt-4']) !!}
{!! Form::text('google_link', null, [
    'class' => 'form-control form-control-sm',
    'placeholder' => 'googel_link...',
]) !!}
@error('google_link')
    <p class="text-danger position-absolute"><small>{{ $message }}</small></p>
@enderror

{!! Form::label('photo', 'Photo', ['class' => 'mt-4']) !!}
{!! Form::file('photo', ['class' => 'member_photo form-control form-control-sm']) !!}
@error('photo')
    <p class="text-danger position-absolute"><small>{{ $message }}</small></p>
@enderror

<div id="member_photo" class="mt-2" style="display: none">
    <img id="show_member_photo" alt="">
</div>


@push('script')
    <script>
        $('.member_photo').on('change', function(e) {
            let files = e.target.files[0]
            files = URL.createObjectURL(files)
            $('#show_member_photo').attr('src', files)
            $('#member_photo').show()
        })
    </script>
@endpush

resources/views/backend/modules/team/index.blade.php
@extends('backend.layout.master')
@section('title', 'Team Member List')
@section('contant')
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header d-flex justify-content-between">
                        <h4> @yield('title')</h4>
                        <a href="{{ route('teams.create') }}">
                            <button class="btn btn-sm btn-success"><i class="fa-solid fa-plus    "></i></button>
                        </a>
                    </div>
                    <div class="card-body">
                        <table class="table table-hover table-striped table-bordered table-sm pt-2" id="my_table">
                            <thead>
                                <tr>
                                    <th> SL </th>
                                    <th> Name </th>
                                    <th> Skills </th>
                                    <th> Status </th>
                                    <th> Email </th>
                                    <th> photo </th>
                                    <th> Time </th>
                                    <th> Action </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($teamMember as $model)
                                    @php
                                        $stats = $model->status;
                                        $create = $model->created_at;
                                        $update = $model->updated_at;
                                    @endphp
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $model->name }}</td>
                                        <td class="text-danger">{{ $model->skills }}</td>
                                        <td>
                                            <div class="form-check form-switch">
                                                <input class="form-check-input" value="{{ $model->id }}" type="checkbox"
                                                    name="status" <?php echo $stats == 1 ? 'checked' : ''; ?> role="switch"
                                                    id="flexSwitchCheckDefault">
                                            </div>
                                        </td>
                                        <td>{{ $model->email }}</td>
                                        <td> <img style="width: 75px" src="{{ asset('image/team/' . $model->photo) }}"
                                                alt="  {{ $model->name }}">
                                        </td>
                                        <td>
                                            <p class="mb-0 text-success">
                                                <small> {{ $create->toDayDateTimeString() }} </small>
                                            </p>
                                            <p class="mb-0">
                                                <small>
                                                    {{ $create == $model->update ? 'Not updated yet' : $update->toDayDateTimeString() }}
                                                </small>
                                            </p>
                                        </td>
                                        <td>
                                            <div class="d-flex justify-content-center">
                                                <a href="{{ route('member.show', $model->id) }}">
                                                    <button class="btn btn-success btn-sm me-1"><i
                                                            class="fa-solid fa-eye    "></i></button>
                                                </a>
                                                <a href="{{ route('member.edit', $model->id) }}">
                                                    <button class="btn btn-warning btn-sm me-1"><i
                                                            class="fa-sloid fa-edit    "></i></button>
                                                </a>
                                                {!! Form::open([
                                                    'method' => 'delete',
                                                    'id' => 'member_delete_form_' . $model->id,
                                                    'route' => ['teams.destroy', $model->id],
                                                ]) !!}
                                                {!! Form::button('<i class="fa-solid fa-trash"></i>', [
                                                    'class' => 'btn btn-danger btn-sm member-select-btn',
                                                    'data-id' => $model->id,
                                                    'id' => 'member_delete_btn_' . $model->id,
                                                ]) !!}
                                                {!! Form::close() !!}
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('script')
    <script>
        $(document).ready(function() {
            $('#my_table').DataTable();
        });
        $('input[name=status]').on('change', function() {
            let mode = $(this).prop('checked') == true ? 1 : 2;
            let id = $(this).val()
            $.ajax({
                url: "{{ route('member.status') }}",
                type: "POST",
                data: {
                    _token: '{{ csrf_token() }}',
                    mode: mode,
                    value: id,
                },
                success: function(response) {
                    if (response.status == 1) {
                        Swal.fire({
                            position: 'top-end',
                            icon: 'success',
                            toast: true,
                            title: 'Member Status active Successfully',
                            showConfirmButton: false,
                            timer: 2000
                        })
                    } else {
                        Swal.fire({
                            position: 'top-end',
                            icon: 'warning',
                            toast: true,
                            title: 'Member Status inactive Successfully',
                            showConfirmButton: false,
                            timer: 2000
                        })
                    }
                }
            })
        })
        $('.member-select-btn').on('click', function() {
            let id = $(this).attr('data-id')
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    $('#member_delete_form_' + id).submit()
                }
            })
        })
    </script>
@endpush

@if (Session::has('msg'))
    @push('script')
        <script>
            Swal.fire({
                position: 'top-end',
                toast: true,
                icon: '<?php echo session('cls'); ?>',
                title: '<?php echo session('msg'); ?>',
                showConfirmButton: false,
                timer: 2000
            })
        </script>
    @endpush
@endif

resources/views/backend/modules/team/show.blade.php
@extends('backend.layout.master')
@section('title', 'Member Details')
@section('contant')
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h4>@yield('title')</h4>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped table-hover table-bordered table-sm">
                            <tbody>
                                <tr>
                                    <th> ID</th>
                                    <td> {{ $ourTeam->id }}</td>
                                </tr>
                                <tr>
                                    <th> Member Name</th>
                                    <td> {{ ucfirst($ourTeam->name) }}</td>
                                </tr>
                                <tr>
                                    <th> Skills </th>
                                    <td> {{ ucfirst($ourTeam->skills) }}</td>
                                </tr>
                                <tr>
                                    <th> Email </th>
                                    <td> {{ $ourTeam->email }}</td>
                                </tr>
                                <tr>
                                    @php
                                        $status = $ourTeam->status;
                                    @endphp
                                    <th> Status </th>
                                    @if ($status == 1)
                                        <td class="text-success"> Active </td>
                                    @else
                                        <td class="text-danger"> Inactive </td>
                                    @endif

                                </tr>
                                <tr>
                                    <th> Facebook </th>
                                    <td> {{ $ourTeam->fb_link }}</td>
                                </tr>
                                <tr>
                                    <th> Twitter </th>
                                    <td> {{ $ourTeam->twitter_link }}</td>
                                </tr>
                                <tr>
                                    <th> Linkdin </th>
                                    <td> {{ $ourTeam->linkdin_link }}</td>
                                </tr>
                                <tr>
                                    <th> Google </th>
                                    <td> {{ $ourTeam->google_link }}</td>
                                </tr>
                                <tr>
                                    <th> Created At </th>
                                    <td> {{ Carbon\Carbon::parse($ourTeam->created_at)->format('d-M-Y') }}</td>
                                </tr>
                                <tr>
                                    <th> Updated At </th>
                                    <td> {{ $ourTeam->updated_at->toDayDateTimeString() }}</td>
                                </tr>
                            </tbody>
                        </table>
                        <a href="{{ route('teams.index') }}">
                            <button class="btn btn-success btn-sm">Back</button>
                        </a>
                    </div>
                </div>


            </div>
        </div>
    </div>
@endsection