routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BannerController;
use App\Http\Controllers\CouponController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\WishlistController;
use App\Http\Controllers\ListBannerController;
use App\Http\Controllers\FetureBanneController;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\SingleBannerController;
use App\Http\Controllers\Backend\BrandController;
use App\Http\Controllers\Backend\OrderController;
use App\Http\Controllers\Frontend\CartController;
use App\Http\Controllers\Backend\AboutUsController;
use App\Http\Controllers\Backend\BackendController;
use App\Http\Controllers\Backend\OurTeamController;
use App\Http\Controllers\Backend\ProductController;
use App\Http\Controllers\Backend\SettingController;
use App\Http\Controllers\Backend\CategoryController;
use App\Http\Controllers\Backend\ShippingController;
use App\Http\Controllers\Frontend\CheckOutController;
use App\Http\Controllers\Frontend\FrontendController;
use App\Http\Controllers\Backend\SubCategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [FrontendController::class, 'index'])->name('front.index');
Route::get('/categories/{slug}', [FrontendController::class, 'categories'])->name('front.categories');
Route::get('/single-product/{slug}', [FrontendController::class, 'singleProduct'])->name('single.product');
Route::get('/product-brand/{slug}', [FrontendController::class, 'productBrand'])->name('product.brand');
Route::post('/quick-view', [FrontendController::class, 'quickView'])->name('quick.view');

// review section
Route::post('/product-review/{slug}', [FrontendController::class, 'productriview'])->name('review.store');

Route::get('/user/login', [FrontendController::class, 'userLogin'])->name('user.login');
Route::post('/user/submit', [FrontendController::class, 'loginSubmit'])->name('login.submit');
Route::post('/register/submit', [UserController::class, 'store'])->name('register.submit');
Route::get('/user/logout', [FrontendController::class, 'userLogout'])->name('user.logout');

// Auto Search Section
Route::get('auto-search', [FrontendController::class, 'autoSearch'])->name('auto.search');
Route::post('search', [FrontendController::class, 'search'])->name('search');

//WishList section
Route::get('wishlists', [WishlistController::class, 'create'])->name('wishlist');
Route::post('wishlist/store', [WishlistController::class, 'store'])->name('wish.store');
Route::post('wishlist/delete', [WishlistController::class, 'delete'])->name('wishlist.delete');
Route::post('move-to-cart', [WishlistController::class, 'moveToCart'])->name('move.cart');

// CheckOut Section Start
Route::get('check-out', [CheckOutController::class, 'checkOut1'])->name('chechkout1');
Route::post('checkout-one', [CheckOutController::class, 'checkOut1Store'])->name('checkout1.store');
Route::post('checkout-two', [CheckOutController::class, 'checkOut2Store'])->name('checkout2.store');
Route::post('checkout-three', [CheckOutController::class, 'checkOut3Store'])->name('checkout3.store');
Route::post('checkout-four', [CheckOutController::class, 'checkOut4Store'])->name('checkout4.store');
Route::get('checkout-complete/{order}', [CheckOutController::class, 'checkOutComplete'])->name('checkout.complete');

//cart Section
Route::post('user/cart/store', [CartController::class, 'cartStore'])->name('cart.store');

Route::post('product-details', [FrontendController::class, 'sizeFilter'])->name('size.filter');

// About us
Route::get('about-us', [FrontendController::class, 'aboutUs'])->name('about.us');
// Contact Section
Route::get('contact-us', [FrontendController::class, 'contactUs'])->name('contactUs');
Route::post('contact', [ContactController::class, 'contactStore'])->name('contact.store');
// Shop Section
Route::get('shop', [FrontendController::class, 'shop'])->name('shop');
Route::post('shop-filter', [FrontendController::class, 'shopFilter'])->name('shop.filter');

Route::group(['prefix' => 'user', 'middleware' => 'auth'], function () {
    Route::get('dashboard', [UserController::class, 'userAccount'])->name('user.dashboard');


    //cart Section
    Route::post('cart/delete', [CartController::class, 'cartDelete'])->name('cart.delete');
    Route::get('cart/details', [CartController::class, 'cartDetails'])->name('cart.details');
    Route::post('cart-update', [CartController::class, 'cartUpdate'])->name('cart.update');

    // coupon section
    Route::post('coupon-add', [CartController::class, 'couponAdd'])->name('coupon.addd');



    //update user Section
    Route::get('orders', [UserController::class, 'userOrder'])->name('user.orders');
    Route::get('account-deatils', [UserController::class, 'userDeatils'])->name('user.deatils');
    Route::post('update-user-address/{id}', [UserController::class, 'updateAdress'])->name('userAddress.update');
    Route::post('update-account/{id}', [UserController::class, 'updateAccount'])->name('update.account');
    Route::get('wishlists', [UserController::class, 'userWishlist'])->name('user.wishlist');

    // coupon Controller
    Route::resource('cupon', CouponController::class);
    Route::post('coupon-status', [CouponController::class, 'couponStatus'])->name('coupon.status');
});


// Backend Section
Route::group(['prefix' => 'dashboard', 'middleware' => ['auth', 'admin']], function () {
    Route::get('/', [BackendController::class, 'index'])->name('dashboard.index');

    // Category Route
    Route::resource('categories', CategoryController::class);
    Route::post('categories-status', [CategoryController::class, 'categoryStatus'])->name('category.status');


    //Sub Category Route
    Route::resource('sub-categories', SubCategoryController::class);
    Route::post('sub-categories-status', [SubCategoryController::class, 'subCategoryStatus'])->name('subCategory.status');
    // Route::get('get-sub-categories/{id}', [SubCategoryController::class, 'subCategory']);

    //Brand Route
    Route::resource('brand', BrandController::class);
    Route::post('brand-status', [BrandController::class, 'brandStatus'])->name('brand.status');

    //Product Route
    Route::resource('products', ProductController::class);
    Route::post('products-status', [ProductController::class, 'productStatus'])->name('product.status');

    // Product Attribute section
    Route::get('add-product-attribute/{id}', [ProductController::class, 'productAttribute'])->name('product.attribute');
    Route::post('product-attribute-store/{id}', [ProductController::class, 'attributeStore'])->name('attribute.store');
    Route::get('product-attributes', [ProductController::class, 'attributeList'])->name('productAttr.index');
    Route::delete('product-attribute-delete/{id}', [ProductController::class, 'attributeDelete'])->name('attribute.delete');

    //User Route
    Route::resource('user', UserController::class);
    Route::post('user-type', [UserController::class, 'userType'])->name('user.type');

    //Banner Route
    Route::resource('banners', BannerController::class);
    Route::post('banners-status', [BannerController::class, 'bannerStatus'])->name('banner.status');

    // Single Banner
    Route::resource('single-banner', SingleBannerController::class);
    Route::post('single-banners-status', [SingleBannerController::class, 'singleStatus'])->name('single.status');

    // List Banner Route
    Route::resource('list-banner', ListBannerController::class);
    Route::post('list-banner-status', [ListBannerController::class, 'listBannerStatus'])->name('list-banner.status');

    // Feature product banner

    // Route::resource('feature-banner', FetureBanneController::class);
    Route::get('feature-banner/create', [FetureBanneController::class, 'create'])->name('feature-banner.create');
    Route::post('feature-banner', [FetureBanneController::class, 'store'])->name('feature-banner.store');
    Route::get('feature-banner', [FetureBanneController::class, 'index'])->name('feature-banner.index');
    Route::get('feature-banner/{id}', [FetureBanneController::class, 'show'])->name('feature-banner.show');
    Route::get('feature-banner/{id}/edit', [FetureBanneController::class, 'edit'])->name('feature-banner.edit');
    Route::put('feature-banner/{id}', [FetureBanneController::class, 'update'])->name('feature-banner.update');
    Route::delete('feature-banner/{id}', [FetureBanneController::class, 'destroy'])->name('feature-banner.destroy');

    Route::post('feature-status', [FetureBanneController::class, 'featureStatus'])->name('feature.status');

    //Order Section
    Route::resource('order', OrderController::class);
    Route::post('order-status', [OrderController::class, 'orderStatus'])->name('order.status');
    Route::get('order-search', [OrderController::class, 'orderSearch'])->name('order.search');

    //Setting Section
    Route::get('setting', [SettingController::class, 'settingEdit'])->name('setting.edit');
    Route::post('setting', [SettingController::class, 'settingStore'])->name('setting.store');

    // Shippiong Route
    Route::resource('shippings', ShippingController::class);
    Route::post('shipping-status', [ShippingController::class, 'shippingStatus'])->name('shipping.status');

    // About us Section
    Route::get('about-us-create', [AboutUsController::class, 'edit'])->name('about.create');
    Route::post('about-us', [AboutUsController::class, 'aboutUpdate'])->name('aboutus.store');

    // Team Membar Secction
    Route::resource('teams', OurTeamController::class);
    Route::get('member-details/{id}', [OurTeamController::class, 'show'])->name('member.show');

app/Models/Banner.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Banner extends Model
{
    use HasFactory;

    protected $guarded = [];
}

app/Http/Controllers/BannerController.php
<?php

namespace App\Http\Controllers;

use App\Helper\Helper;
use App\Models\Banner;
use Illuminate\Support\Str;
use Illuminate\Http\Request;

class BannerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $banners = Banner::orderBy('id', 'desc')->get();
        return view('backend.modules.banner.index', compact('banners'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.modules.banner.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $banner_data = $request->all();

        if ($request->file('photo')) {
            $photo = $request->file('photo');
            $width = 590;
            $height = 430;
            $path = 'image/banner/';
            $name = 'banner-img-' . rand(11111, 99999) . '.webp';
            $banner_data['photo'] = $name;
            Helper::uploadImage($photo, $width, $height, $path, $name);
        }
        Banner::create($banner_data);
        session()->flash('msg', 'banner create successfully');
        session()->flash('cls', 'success');
        return redirect()->route('banners.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Banner  $banner
     * @return \Illuminate\Http\Response
     */
    public function show(Banner $banner)
    {
        // dd($banner);
        return view('backend.modules.banner.show', compact('banner'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Banner  $banner
     * @return \Illuminate\Http\Response
     */
    public function edit(Banner $banner)
    {
        // dd($banner);
        return view('backend.modules.banner.edit', compact('banner'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Banner  $banner
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Banner $banner)
    {
        $update_data = $request->all();
        $update_data['name'] = $request->input('name');
        if ($request->file('photo')) {
            $photo = $request->file('photo');
            $width = 590;
            $height = 430;
            $path = 'image/banner/';
            $name = 'banner-img-' . rand(22222, 99999) . '.webp';
            $update_data['photo'] = $name;

            if ($banner->photo != null) {
                Helper::unlinkImage($path, $banner->photo);
            }
            Helper::uploadImage($photo, $width, $height, $path, $name);
        }
        $banner->update($update_data);
        session()->flash('msg', 'Banner updated sucessfuly');
        session()->flash('cls', 'success');
        return redirect()->route('banners.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Banner  $banner
     * @return \Illuminate\Http\Response
     */
    public function destroy(Banner $banner)
    {
        if ($banner->photo != null) {
            $path = 'image/banner/';
            Helper::unlinkImage($path, $banner->photo);
        }
        $banner->delete();
        session()->flash('msg', 'Banner delete successfully');
        session()->flash('cls', 'warning');
        return redirect()->back();
    }


    /**
     * Summary of bannerStatus
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function bannerStatus(Request $request)
    {
        $mode = $request->mode;
        if ($mode == 1) {
            Banner::where('id', $request->id)->update(['status' => 1]);
        } else {
            Banner::where('id', $request->id)->update(['status' => 2]);
        }
        return response()->json(['msg' => 'Banner status updated successfully', 'status' => $mode]);
    }
}

resources/views/backend/modules/banner/create.blade.php
@extends('backend.layout.master')

@section('title', 'Banner Create')

@section('contant')
    <div class="container ">
        <div class="row justify-content-center py-5">
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-header d-flex justify-content-between">
                        <h4> @yield('title')</h4>
                        <a href="{{ route('banners.index') }}">
                            <button class="btn btn-sm btn-success">Back</button>
                        </a>
                    </div>
                    <div class="card-body">
                        {!! Form::open(['route' => 'banners.store', 'method' => 'post', 'files' => true]) !!}
                        @include('backend.modules.banner.form')
                        <div class="show-banner mt-2" style="display: none">
                            <img id="banner_img" alt="">
                        </div>
                        {!! Form::button('Create Banner', ['class' => 'btn btn-sm btn-success mt-4', 'type' => 'submit']) !!}
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/modules/banner/edit.blade.php
@extends('backend.layout.master')

@section('title', 'Update Banner')

@section('contant')
    <div class="conatiner">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-header">
                        <h4> @yield('title')</h4>
                    </div>
                    <div class="card-body">
                        {!! Form::model($banner, ['route' => ['banners.update', $banner->id], 'method' => 'put', 'files' => true]) !!}
                        @include('backend.modules.banner.form')
                        <div class="row py-3 ">
                            <div class="col-lg-6">
                                <div class="old-img">
                                    <h6>Old Image</h6>
                                    <hr class="my-2 text-danger">
                                    <img src="{{ asset('image/banner/' . $banner->photo) }}" alt="">
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="show-banner" style="display: none">
                                    <h6>new photo</h6>
                                    <hr class="my-2 me-5 text-danger">
                                    <img id="banner_img" alt="">
                                </div>
                            </div>
                        </div>
                        {!! Form::button('Update banner', ['class' => 'mt-4 mb-2 btn btn-warning btn-sm', 'type' => 'submit']) !!}
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/modules/banner/form.blade.php
{!! Form::label('name', 'Title') !!}
{!! Form::text('name', null, [
    'class' => 'form-control form-control-sm',
    'placeholder' => 'Insert banner title',
]) !!}
@error('name')
    <p><small>{{ $message }}</small></p>
@enderror
{!! Form::label('status', 'Status', ['class' => 'mt-4']) !!}
{!! Form::select('status', [1 => 'Active', 2 => 'Inactive'], null, [
    'class' => 'form-select form-select-sm ',
    'placeholder' => 'Insert banner status',
]) !!}
@error('status')
    <p><small>{{ $message }}</small></p>
@enderror
{!! Form::label('price', 'Price', ['class' => 'mt-4']) !!}
{!! Form::number('price', null, [
    'class' => 'form-control form-control-sm ',
    'placeholder' => 'Insert price',
]) !!}
@error('status')
    <p><small>{{ $message }}</small></p>
@enderror

{!! Form::label('short_description', 'Short Description', ['class' => 'mt-4']) !!}
{!! Form::textarea('short_description', null, [
    'class' => 'form-control form-control-sm',
    'placeholder' => 'Insert banner short description',
]) !!}
{!! Form::label('description', 'Description', ['class' => 'mt-4']) !!}
{!! Form::textarea('description', null, [
    'class' => 'form-control form-control-sm',
    'placeholder' => 'Insert banner description',
]) !!}
{!! Form::label('photo', 'Photo', ['class' => 'mt-4']) !!}
{!! Form::file('photo', ['id' => 'photo', 'class' => 'form-control form-control-sm']) !!}
@error('photo')
    <p><small>{{ $message }}</small></p>
@enderror


@push('script')
    <script>
        $('#photo').on('change', function(e) {
            let file = e.target.files[0]
            file = URL.createObjectURL(file)
            $('#banner_img').attr('src', file)
            $('.show-banner').show()
        })
    </script>
@endpush

resources/views/backend/modules/banner/index.blade.php
@extends('backend.layout.master')

@section('title', 'Banner List')

@section('contant')
    <div class="container">
        <div class="row py-5">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header d-flex justify-content-between">
                        <h4>@yield('title')</h4>
                        <a href="{{ route('banners.create') }}">
                            <button class="btn btn-sm btn-success">create</button>
                        </a>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>SL</th>
                                    <th>Title</th>
                                    <th>Status</th>
                                    <th>Price</th>
                                    <th>Description</th>
                                    <th>Short Description</th>
                                    <th>Photo</th>
                                    <th>Time</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($banners as $banner)
                                    @php
                                        $create = $banner->created_at;
                                        $update = $banner->updated_at;
                                        $status = $banner->status;
                                    @endphp
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $banner->name }}</td>
                                        <td class="text-center">
                                            <div class="form-check form-switch">
                                                <input class="form-check-input" value="{{ $banner->id }}" type="checkbox"
                                                    name="status" <?php echo $status == 1 ? 'checked' : ''; ?> role="switch"
                                                    id="flexSwitchCheckDefault">
                                            </div>
                                        </td>
                                        <td>{{ $banner->price }}</td>
                                        <td>{{ $banner->description }}</td>
                                        <td>{{ $banner->short_description }}</td>
                                        <td><img width="75px" src="{{ asset('image/banner/' . $banner->photo) }}"
                                                alt=""></td>
                                        <td>
                                            <p class="mb-0"><small>{{ $create->toDayDateTimeString() }}</small></p>
                                            <p class="mb-0 text-success">
                                                <small>{{ $create == $update ? 'Not Updated yet' : $update->toDayDateTimeString() }}</small>
                                            </p>
                                        </td>
                                        <td>
                                            <div class="d-flex">
                                                <a href="{{ route('banners.show', $banner->id) }}">
                                                    <button class="btn btn-sm btn-success me-1">
                                                        <i class="fa-solid fa-eye    "></i>
                                                    </button>
                                                </a>
                                                <a href="{{ route('banners.edit', $banner->id) }}">
                                                    <button class="btn btn-sm btn-warning me-1">
                                                        <i class="fa-sloid fa-edit    "></i>
                                                    </button>
                                                </a>
                                                {!! Form::open([
                                                    'method' => 'delete',
                                                    'id' => 'banner_delete_form_' . $banner->id,
                                                    'route' => ['banners.destroy', $banner->id],
                                                ]) !!}
                                                {!! Form::button('<i class="fa-solid fa-trash"></i>', [
                                                    'class' => 'btn btn-sm btn-danger banner_delete_btn',
                                                    'data-id' => $banner->id,
                                                    'id' => 'banner_delete_btn_' . $banner->id,
                                                ]) !!}
                                                {!! Form::close() !!}
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @if (Session::has('msg'))
        @push('script')
            <script>
                Swal.fire({
                    position: 'top-end',
                    toast: true,
                    icon: '<?php echo session('cls'); ?>',
                    title: '<?php echo session('msg'); ?>',
                    showConfirmButton: false,
                    timer: 2000
                })
            </script>
        @endpush
    @endif
@endsection

@push('script')
    <script>
        $('.banner_delete_btn').on('click', function() {
            let id = $(this).attr('data-id')
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    $('#banner_delete_form_' + id).submit()
                }
            })
        })



        $("input[name=status]").on('change', function() {
            let value = $(this).prop('checked') == true ? 1 : 2;
            let id = $(this).val();
            $.ajax({
                url: "{{ route('banner.status') }}",
                type: "POST",
                data: {
                    _token: "{{ csrf_token() }}",
                    mode: value,
                    id: id,
                },
                success: function(response) {
                    if (response.status) {
                        Swal.fire({
                            position: 'top-end',
                            icon: 'success',
                            toast: true,
                            title: response.msg,
                            showConfirmButton: false,
                            timer: 2000
                        })
                    }
                }
            })
        })
    </script>
@endpush

resources/views/backend/modules/banner/show.blade.php
@extends('backend.layout.master')

@section('title', 'Slider Show')

@section('contant')
    <div class="container">
        <div class="row justify-content-center py-5">
            <div class="col-lg-7">
                <div class="card">
                    <div class="card-header">
                        <h4>@yield('title')</h4>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped table-bordered table-hover table-sm">
                            <tbody>
                                @php
                                    $status = $banner->status;
                                    $create = $banner->created_at;
                                    $update = $banner->updated_at;
                                @endphp
                                <tr>
                                    <th>ID </th>
                                    <td>{{ $banner->id }}</td>
                                </tr>
                                <tr>
                                    <th> Title </th>
                                    <td>{{ $banner->name }}</td>
                                </tr>
                                <tr>
                                    <th> status </th>
                                    @if ($status == 1)
                                        <td class="text-success">Active</td>
                                    @else
                                        <td class="text-danger">Inactive</td>
                                    @endif
                                </tr>
                                <tr>
                                    <th> Price </th>
                                    <td>{{ $banner->price }}</td>
                                </tr>
                                <tr>
                                    <th> Short Description </th>
                                    <td>{{ $banner->short_description }}</td>
                                </tr>
                                <tr>
                                    <th> Description </th>
                                    <td>{{ $banner->description }}</td>
                                </tr>
                                <tr>
                                    <th> Created At </th>
                                    <td>{{ $banner->created_at->toDayDateTimeString() }}</td>
                                </tr>
                                <tr>
                                    <th> Created At </th>
                                    @if ($create == $update)
                                        <td class="text-danger">Not updated yet</td>
                                    @else
                                        <td class="text-success">{{ $update->toDayDateTimeString() }}</td>
                                    @endif
                                </tr>
                                <tr>
                                    <th>Photo</th>
                                    <td><img width="190px" src="{{ asset('image/banner/' . $banner->photo) }}"
                                            alt="{{ $banner->name }}">
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <a href="{{ route('banners.index') }}">
                            <button class="btn btn-success btn-sm">Back</button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection