routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BannerController;
use App\Http\Controllers\CouponController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\WishlistController;
use App\Http\Controllers\ListBannerController;
use App\Http\Controllers\FetureBanneController;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\SingleBannerController;
use App\Http\Controllers\Backend\BrandController;
use App\Http\Controllers\Backend\OrderController;
use App\Http\Controllers\Frontend\CartController;
use App\Http\Controllers\Backend\AboutUsController;
use App\Http\Controllers\Backend\BackendController;
use App\Http\Controllers\Backend\OurTeamController;
use App\Http\Controllers\Backend\ProductController;
use App\Http\Controllers\Backend\SettingController;
use App\Http\Controllers\Backend\CategoryController;
use App\Http\Controllers\Backend\ShippingController;
use App\Http\Controllers\Frontend\CheckOutController;
use App\Http\Controllers\Frontend\FrontendController;
use App\Http\Controllers\Backend\SubCategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [FrontendController::class, 'index'])->name('front.index');
Route::get('/categories/{slug}', [FrontendController::class, 'categories'])->name('front.categories');
Route::get('/single-product/{slug}', [FrontendController::class, 'singleProduct'])->name('single.product');
Route::get('/product-brand/{slug}', [FrontendController::class, 'productBrand'])->name('product.brand');
Route::post('/quick-view', [FrontendController::class, 'quickView'])->name('quick.view');

// review section
Route::post('/product-review/{slug}', [FrontendController::class, 'productriview'])->name('review.store');

Route::get('/user/login', [FrontendController::class, 'userLogin'])->name('user.login');
Route::post('/user/submit', [FrontendController::class, 'loginSubmit'])->name('login.submit');
Route::post('/register/submit', [UserController::class, 'store'])->name('register.submit');
Route::get('/user/logout', [FrontendController::class, 'userLogout'])->name('user.logout');

// Auto Search Section
Route::get('auto-search', [FrontendController::class, 'autoSearch'])->name('auto.search');
Route::post('search', [FrontendController::class, 'search'])->name('search');

//WishList section
Route::get('wishlists', [WishlistController::class, 'create'])->name('wishlist');
Route::post('wishlist/store', [WishlistController::class, 'store'])->name('wish.store');
Route::post('wishlist/delete', [WishlistController::class, 'delete'])->name('wishlist.delete');
Route::post('move-to-cart', [WishlistController::class, 'moveToCart'])->name('move.cart');

// CheckOut Section Start
Route::get('check-out', [CheckOutController::class, 'checkOut1'])->name('chechkout1');
Route::post('checkout-one', [CheckOutController::class, 'checkOut1Store'])->name('checkout1.store');
Route::post('checkout-two', [CheckOutController::class, 'checkOut2Store'])->name('checkout2.store');
Route::post('checkout-three', [CheckOutController::class, 'checkOut3Store'])->name('checkout3.store');
Route::post('checkout-four', [CheckOutController::class, 'checkOut4Store'])->name('checkout4.store');
Route::get('checkout-complete/{order}', [CheckOutController::class, 'checkOutComplete'])->name('checkout.complete');

//cart Section
Route::post('user/cart/store', [CartController::class, 'cartStore'])->name('cart.store');

Route::post('product-details', [FrontendController::class, 'sizeFilter'])->name('size.filter');

// About us
Route::get('about-us', [FrontendController::class, 'aboutUs'])->name('about.us');
// Contact Section
Route::get('contact-us', [FrontendController::class, 'contactUs'])->name('contactUs');
Route::post('contact', [ContactController::class, 'contactStore'])->name('contact.store');
// Shop Section
Route::get('shop', [FrontendController::class, 'shop'])->name('shop');
Route::post('shop-filter', [FrontendController::class, 'shopFilter'])->name('shop.filter');

Route::group(['prefix' => 'user', 'middleware' => 'auth'], function () {
    Route::get('dashboard', [UserController::class, 'userAccount'])->name('user.dashboard');


    //cart Section
    Route::post('cart/delete', [CartController::class, 'cartDelete'])->name('cart.delete');
    Route::get('cart/details', [CartController::class, 'cartDetails'])->name('cart.details');
    Route::post('cart-update', [CartController::class, 'cartUpdate'])->name('cart.update');

    // coupon section
    Route::post('coupon-add', [CartController::class, 'couponAdd'])->name('coupon.addd');



    //update user Section
    Route::get('orders', [UserController::class, 'userOrder'])->name('user.orders');
    Route::get('account-deatils', [UserController::class, 'userDeatils'])->name('user.deatils');
    Route::post('update-user-address/{id}', [UserController::class, 'updateAdress'])->name('userAddress.update');
    Route::post('update-account/{id}', [UserController::class, 'updateAccount'])->name('update.account');
    Route::get('wishlists', [UserController::class, 'userWishlist'])->name('user.wishlist');

    // coupon Controller
    Route::resource('cupon', CouponController::class);
    Route::post('coupon-status', [CouponController::class, 'couponStatus'])->name('coupon.status');
});


// Backend Section
Route::group(['prefix' => 'dashboard', 'middleware' => ['auth', 'admin']], function () {
    Route::get('/', [BackendController::class, 'index'])->name('dashboard.index');

    // Category Route
    Route::resource('categories', CategoryController::class);
    Route::post('categories-status', [CategoryController::class, 'categoryStatus'])->name('category.status');


    //Sub Category Route
    Route::resource('sub-categories', SubCategoryController::class);
    Route::post('sub-categories-status', [SubCategoryController::class, 'subCategoryStatus'])->name('subCategory.status');
    // Route::get('get-sub-categories/{id}', [SubCategoryController::class, 'subCategory']);

    //Brand Route
    Route::resource('brand', BrandController::class);
    Route::post('brand-status', [BrandController::class, 'brandStatus'])->name('brand.status');

    //Product Route
    Route::resource('products', ProductController::class);
    Route::post('products-status', [ProductController::class, 'productStatus'])->name('product.status');

    // Product Attribute section
    Route::get('add-product-attribute/{id}', [ProductController::class, 'productAttribute'])->name('product.attribute');
    Route::post('product-attribute-store/{id}', [ProductController::class, 'attributeStore'])->name('attribute.store');
    Route::get('product-attributes', [ProductController::class, 'attributeList'])->name('productAttr.index');
    Route::delete('product-attribute-delete/{id}', [ProductController::class, 'attributeDelete'])->name('attribute.delete');

    //User Route
    Route::resource('user', UserController::class);
    Route::post('user-type', [UserController::class, 'userType'])->name('user.type');

    //Banner Route
    Route::resource('banners', BannerController::class);
    Route::post('banners-status', [BannerController::class, 'bannerStatus'])->name('banner.status');

    // Single Banner
    Route::resource('single-banner', SingleBannerController::class);
    Route::post('single-banners-status', [SingleBannerController::class, 'singleStatus'])->name('single.status');

    // List Banner Route
    Route::resource('list-banner', ListBannerController::class);
    Route::post('list-banner-status', [ListBannerController::class, 'listBannerStatus'])->name('list-banner.status');

    // Feature product banner

    // Route::resource('feature-banner', FetureBanneController::class);
    Route::get('feature-banner/create', [FetureBanneController::class, 'create'])->name('feature-banner.create');
    Route::post('feature-banner', [FetureBanneController::class, 'store'])->name('feature-banner.store');
    Route::get('feature-banner', [FetureBanneController::class, 'index'])->name('feature-banner.index');
    Route::get('feature-banner/{id}', [FetureBanneController::class, 'show'])->name('feature-banner.show');
    Route::get('feature-banner/{id}/edit', [FetureBanneController::class, 'edit'])->name('feature-banner.edit');
    Route::put('feature-banner/{id}', [FetureBanneController::class, 'update'])->name('feature-banner.update');
    Route::delete('feature-banner/{id}', [FetureBanneController::class, 'destroy'])->name('feature-banner.destroy');

    Route::post('feature-status', [FetureBanneController::class, 'featureStatus'])->name('feature.status');

    //Order Section
    Route::resource('order', OrderController::class);
    Route::post('order-status', [OrderController::class, 'orderStatus'])->name('order.status');
    Route::get('order-search', [OrderController::class, 'orderSearch'])->name('order.search');

    //Setting Section
    Route::get('setting', [SettingController::class, 'settingEdit'])->name('setting.edit');
    Route::post('setting', [SettingController::class, 'settingStore'])->name('setting.store');

    // Shippiong Route
    Route::resource('shippings', ShippingController::class);
    Route::post('shipping-status', [ShippingController::class, 'shippingStatus'])->name('shipping.status');

    // About us Section
    Route::get('about-us-create', [AboutUsController::class, 'edit'])->name('about.create');
    Route::post('about-us', [AboutUsController::class, 'aboutUpdate'])->name('aboutus.store');

    // Team Membar Secction
    Route::resource('teams', OurTeamController::class);
    Route::get('member-details/{id}', [OurTeamController::class, 'show'])->name('member.show');

app/Models/Product.php
<?php

namespace App\Models;

use App\Models\Category;
use App\Models\Backend\Brand;
use App\Models\ProductAttribute;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Product extends Model
{
    use HasFactory;

    protected $guarded = [];

    /**
     * Summary of category
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * Summary of subCategory
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function subCategory()
    {
        return $this->belongsTo(SubCategory::class);
    }
    /**
     * Summary of user
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }
    /**
     * Summary of brand
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function brand()
    {
        return $this->belongsTo(Brand::class);
    }

    /**
     * Summary of getCartProduct
     * @param mixed $id
     * @return mixed
     */
    public static function getCartProduct($id)
    {
        return self::where('id', $id)->get()->toArray();
    }

    public function productAttr()
    {
        return $this->hasMany(ProductAttribute::class);
    }
}

resources/views/backend/modules/product/edit.blade.php
@extends('backend.layout.master')
@section('title', 'Product update')
@section('contant')
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-header d-flex justify-content-between">
                        <h4> @yield('title')</h4>
                        <a href="{{ route('products.index') }}">
                            <button class="btn btn-sm btn-success">Back</button>
                        </a>
                    </div>
                    <div class="card-body">
                        {!! Form::model($product, ['method' => 'put', 'route' => ['products.update', $product->id], 'files' => true]) !!}
                        @include('backend.modules.product.form')

                        <div class="row my-3">
                            <div class="col-lg-6">
                                <div class="old-img mb-3">
                                    <h6>old image</h6>
                                    <hr class="my-2 text-danger">
                                    <img src="{{ asset('image/product/thumbnail/' . $product->photo) }}"
                                        alt="{{ $product->photo }}">
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="update-img" style="display: none">
                                    <h6>update image</h6>
                                    <hr class="my-2 text-danger">
                                    <img id="feather_img" alt="">
                                </div>
                            </div>
                        </div>
                        {!! Form::button('Update Product', ['class' => 'btn btn-success btn-sm mt-4', 'type' => 'submit']) !!}
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('script')
    <script>
        $('#photo').on('change', function(e) {
            let photo = e.target.files[0]
            photo = URL.createObjectURL(photo)
            $('#feather_img').attr('src', photo)
            $('.update-img').show()
        })




        let sub_category_id = "<?php echo $product->sub_category_id; ?>"
        const getsubCategories = (id) => {
            axios.get(window.location.origin + '/get-sub-categories/' + id).then(res => {
                let subCategories = res.data.data
                subCategories.map(subCategory => {
                    $('#select_sub_category').append(
                        `<option ${subCategory.id == sub_category_id ? 'selected' : ''} value="${subCategory.id}">${subCategory.name}</option>`
                    )
                })
            })
        }
        let category_id = '<?php echo $product->category_id; ?>'
        getsubCategories(category_id)
        $('#category_select').on('change', function() {
            let id = $(this).val()
            $('#select_sub_category').empty()
            $('#select_sub_category').append('<option value="">Select Sub Category</option>')
            getsubCategories(id)
        })
    </script>
@endpush

resources/views/backend/modules/product/index.blade.php
@extends('backend.layout.master')
@section('title', 'Products List')
@section('contant')
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header d-flex justify-content-between">
                        <h4> @yield('title')</h4>
                        <a href="{{ route('products.create') }}">
                            <button class="btn btn-sm btn-success"><i class="fa-solid fa-plus    "></i></button>
                        </a>
                    </div>
                    <div class="card-body">
                        <table class="table table-hover table-striped table-bordered table-sm pt-2" id="my_table">
                            <thead>
                                <tr>
                                    <th> SL </th>
                                    <th> ID </th>
                                    <th> Name </th>
                                    <th> Status </th>
                                    <th> Description </th>
                                    <th> stock </th>
                                    {{-- <th> Category Name </th>
                                    <th> Sub Category Name </th> --}}
                                    <th> Price </th>
                                    <th> Offer Price </th>
                                    {{-- <th> Discount </th> --}}
                                    <th> size </th>
                                    <th> Photo </th>
                                    <th> Time </th>
                                    <th> Action </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($products as $model)
                                    @php
                                        $stats = $model->status;
                                        $create = $model->created_at;
                                        $update = $model->updated_at;
                                    @endphp
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $model->id }}</td>
                                        <td>{{ $model->title }}</td>
                                        <td>
                                            <div class="form-check form-switch">
                                                <input class="form-check-input" value="{{ $model->id }}" type="checkbox"
                                                    name="status" <?php echo $stats == 1 ? 'checked' : ''; ?> role="switch"
                                                    id="flexSwitchCheckDefault">
                                            </div>
                                        </td>
                                        <td>{!! substr($model->description, 0, 20) . '...' !!}</td>
                                        <td>{{ $model->stock }}</td>
                                        {{-- <td>{{ $model->category->name }}</td>
                                        <td>{{ $model->subCategory->name }}</td> --}}
                                        <td>{{ $model->price }}</td>
                                        <td>{{ $model->offer_price }}</td>
                                        {{-- <td>{{ $model->discount }}</td> --}}
                                        <td>{{ $model->size }}</td>
                                        <td>
                                            <img width="75px"
                                                src="{{ asset('image/product/thumbnail/' . $model->photo) }}"
                                                alt="">
                                        </td>
                                        <td>
                                            <p class="mb-0 text-success">
                                                {{-- <small> {{ $create->toDayDateTimeString() }} </small> --}}
                                            </p>
                                            <p class="mb-0">
                                                <small>
                                                    {{-- {{ $create == $update ? 'Not updated yet' : $update->toDayDateTimeString() }} --}}
                                                </small>
                                            </p>
                                        </td>
                                        <td>
                                            <div class="d-flex justify-content-center">
                                                <a href="{{ route('product.attribute', $model->id) }}"
                                                    title="add attribute">
                                                    <button class="btn btn-info btn-sm me-1"> <i
                                                            class="fa-solid fa-plus    "></i> </button>
                                                </a>
                                                <a href="{{ route('products.show', $model->id) }}">
                                                    <button class="btn btn-success btn-sm me-1">
                                                        <i class="fa-solid fa-eye"></i>
                                                    </button>
                                                </a>
                                                <a href="{{ route('products.edit', $model->id) }}">
                                                    <button class="btn btn-warning btn-sm me-1">
                                                        <i class="fa-solid fa-pen-to-square"></i>
                                                    </button>
                                                </a>
                                                {!! Form::open([
                                                    'method' => 'delete',
                                                    'id' => 'category_delete_form_' . $model->id,
                                                    'route' => ['products.destroy', $model->id],
                                                ]) !!}
                                                {!! Form::button('<i class="fa-solid fa-trash"></i>', [
                                                    'class' => 'btn btn-danger btn-sm category-select-btn',
                                                    'data-id' => $model->id,
                                                    'id' => 'category_delete_btn_' . $model->id,
                                                ]) !!}
                                                {!! Form::close() !!}
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection


@push('script')
    <script>
        $(document).ready(function() {
            $('#my_table').DataTable();
        });

        $('input[name=status]').on('change', function() {
            let mode = $(this).prop('checked') == true ? 1 : 2;
            let value = $(this).val();
            $.ajax({
                url: "{{ route('product.status') }}",
                type: "POST",
                data: {
                    _token: '{{ csrf_token() }}',
                    mode: mode,
                    id: value,
                },
                success: function(response) {
                    if (response.status) {
                        Swal.fire({
                            position: 'top-end',
                            icon: 'success',
                            toast: true,
                            title: response.msg,
                            showConfirmButton: false,
                            timer: 2000
                        })
                    }
                }
            })
        })

        $('.category-select-btn').on('click', function() {
            let id = $(this).attr('data-id')
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    $('#category_delete_form_' + id).submit()
                }
            })
        })
    </script>
@endpush

@if (Session::has('msg'))
    @push('script')
        <script>
            Swal.fire({
                position: 'top-end',
                toast: true,
                icon: '<?php echo session('cls'); ?>',
                title: '<?php echo session('msg'); ?>',
                showConfirmButton: false,
                timer: 2000
            })
        </script>
    @endpush
@endif

resources/views/backend/modules/product/show.blade.php
@extends('backend.layout.master')
@section('title', 'Product Show')
@section('contant')
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h4>@yield('title')</h4>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped table-hover table-bordered table-sm">
                            <tbody>
                                <tr>
                                    <th class="text-danger"> ID</th>
                                    <td> {{ $product->id }}</td>
                                </tr>
                                <tr>
                                    <th class="text-danger"> Product Name </th>
                                    <td> {{ $product->title }}</td>
                                </tr>
                                <tr>
                                    <th class="text-danger"> Slug </th>
                                    <td> {{ $product->slug }}</td>
                                </tr>
                                <tr>
                                    @php
                                        $status = $product->status;
                                    @endphp
                                    <th class="text-danger"> Status </th>
                                    @if ($status == 1)
                                        <td class="text-success"> Active </td>
                                    @else
                                        <td class="text-warning"> Inactive </td>
                                    @endif
                                </tr>
                                <tr>
                                    <th class="text-danger"> Short Description </th>
                                    <td> {!! $product->short_des !!}</td>
                                </tr>
                                <tr>
                                    <th class="text-danger"> Description </th>
                                    <td> {!! $product->description !!}</td>
                                </tr>
                                <tr>
                                    <th class="text-danger"> Stock </th>
                                    <td class="text-primary"> {!! $product->stock !!}</td>
                                </tr>
                                <tr>
                                    <th class="text-danger"> Price </th>
                                    <td class="text-primary"> {!! $product->price !!} TK</td>
                                </tr>
                                <tr>
                                    <th class="text-danger"> Offer Price </th>
                                    <td class="text-primary"> {!! $product->offer_price !!} TK</td>
                                </tr>
                                <tr>
                                    <th class="text-danger"> Discount </th>
                                    <td class="text-primary"> {!! $product->discount !!}</td>
                                </tr>
                                <tr>
                                    <th class="text-danger"> Size </th>
                                    <td class="text-primary"> {!! $product->size !!}</td>
                                </tr>

                                <tr>
                                    <th class="text-danger"> Brand </th>
                                    <td> {!! $product->brand->name !!}</td>
                                </tr>
                                <tr>
                                    <th class="text-danger"> Condition </th>
                                    <td> {!! $product->condition !!}</td>
                                </tr>
                                <tr>
                                    <th class="text-danger"> Category Name </th>
                                    <td> {!! $product->category->name !!}</td>
                                </tr>
                                <tr>
                                    <th class="text-danger"> Sub Category Name </th>
                                    <td> {!! $product->subCategory->name !!}</td>
                                </tr>
                                <tr>
                                    <th class="text-danger"> Created By </th>
                                    <td> {!! $product->user->f_name . ' ' . $product->user->l_name !!}</td>
                                </tr>
                                <tr>
                                    <th class="text-danger"> Created At </th>
                                    <td> {{ $product->created_at->toDayDateTimeString() }}</td>
                                </tr>
                                <tr>
                                    <th class="text-danger"> Updated At </th>
                                    <td> {{ $product->updated_at->toDayDateTimeString() }}</td>
                                </tr>
                                <tr>
                                    <th class="text-danger"> Photo </th>
                                    <td> <img class="product_img"
                                            src="{{ asset('image/product/thumbnail/' . $product->photo) }}" alt="">
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <a href="{{ route('products.index') }}">
                            <button class="btn btn-success">Back</button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection